### PR TITLE
Add: Basic working UMK3 training mode

### PR DESCRIPTION
**Pull request by Ausuri**
Here's a basic working training mode for UMK3. I'll try to keep it short but there are a few nuances:

- Coincidentally the UMK3 maintenance mode is activated exactly the same way as the training mode menu. Holding the coin button down or pressing it four times will enter the game's maintenance menu. It still works but the game must be restarted or a save state must be loaded. This could either be solved by making a special case for UMK3's training menu or NOP'ing out UMK3's maintenance mode call while the script is running. 
- The combo counter in memory works correctly, but for some reason when I run the trainer it's off by 1. Fixing that is on my to-do list but for now I've set comboenabled = false by default. 

Other than that, it seems to work flawlessly. It's still a work in progress and I have a few long-term goals for the Mortal Kombat games. Let me know if you'd like me to make any changes.

### CODE REVIEW

**Comment by peon2** [comment]
Merged.
I don't know much at all about UMK3 or how training is normally done with it. Is it usual for it to always be in maintenace mode while practicing? Will there be a problem with NOPing the maintenance menu?

**Comment by Ausuri** [comment]
Another update, from some reason bringing up the training gui is tied to resetting the machine to the maintenance menu - I have no idea why this would be but I've quadruple checked and it's definitely not a misconfiguration on my part. You can even remove the service menu button binding from fbneo and it will still go to the maintenance menu when the training mode menu gui appears. 

I've looked through the code for the training mode menu and I'm not sure how this can happen. NOPing UMK3's maintenance menu call is still an option, although I from what I've looked at in UMK3's disassembled code it's not a straightforward fix but it's doable I think.

**Comment by peon2** [comment]
I'm not really sure what's going on. Opening the training menu always promts the diagnostics whether it's done through coin or not. I also tried it without your umk3.lua so there would be no chance of any memory being written to, but this also brought the menu up. I'll keep looking, but there's a chance something is going on with fbneo, like a bad driver or something? Older games tend to default to debug/diagnostic/level select menus etc. if they unexpectedly crash and the game can catch it. I still think it's likely something that can be fixed on my end though.

**Comment by Ausuri** [comment]
It looks like you are correct, blocking the input for the maintenance mode doesn't prevent the maintenance menu appearing when the training mode gui is opened. It's likely an issue with FBNeo beyond the scope of the training mode. Although, like you said, there may be a workaround that's possible in the script. 

It may be best the leave UMK3 out of the supported games list until it's resolved, but it's up to you.

**Pull request merged**
