### PR TITLE
Add support for SF2: World Warrior

### PR DESCRIPTION
**Pull request by PopovMark**
This should allow SF2 to work properly with this training mode. All I did was take the CE script and find the right addresses for the timer and health values and put them in there.

### CODE REVIEW

**Comment by peon2** [comment]
Great commit! I was meant to add WW previously but I actually forgot to upload it... I'll make great use of those red health values you found, I didn't have them before.

**Comment by PopovMark** [comment]
BTW, I didn't get them by hand. I got them from the MAME cheat files which are located here:
[http://cheat.retrogames.com/mame_downloads.htm](url)
In there's a bunch of XML files, opening them reveals what memory addresses are changed to get stuff like the infinite time and health cheats working. Specifically the ones to set P1/P2's health to 0.

**Comment by peon2** [comment]
I must have missed it when I looked through that XML before.

**Comment by PopovMark** [comment]
"Drain All Energy Now"'s the name of the cheat that has those values, I believe.
Are there any plans to add Hyper Street Fighter 2, perhaps?

**Comment by peon2** [comment]
sure

**Pull request merged**
